
* 异常
    * 相关类结构
        * Throwable
            * Error
            * Exception
                * RuntimeException
                    * NullPointerException
                    * ArrayIndexOutOfBoundsException
                    * ClassCastException
                    * ArithmeticException
                    * ...
                * 检查异常
                    * 文件异常
                    * SQL异常
                    * ...
    * Throwable 是所有异常的基类
    * Error (错误)一般为系统错误（如虚拟机错误、内存溢出等），出现时程序基本上已经彻底挂掉了，无法在软件内部进行处理
    * Exception 一般为编码、环境、用户操作等问题，可以在软件内部进行恢复
    * RuntimeException (非检查异常、运行时异常)，一般由系统自动抛出，通常是代码错误导致的，应该从逻辑上改进代码
    * NullPointerException 空指针异常
    * ArrayIndexOutOfBoundsException 数组下标越界异常
    * ClassCastException 类型转换异常
    * ArithmeticException 算术异常
    * 引起检查异常的可能有多种多样，通常不是由代码直接造成的，需要手动添加捕获以及处理语句

* 语句：try-catch、try-catch-finally
```
try{
    // 可能引发异常的语句
} catch (Exception e){
    // e.printStackTrace();     // 可以考虑打印出来异常信息
    // exception do
} finally {
    // finally do 
}
```

* 异常抛出
    * throw  实际抛出异常对象
    * throws 声明可能要抛出何种类型的异常（声明）
    ```
    public void 方法名( 参数列表 ) throws 异常列表{
        throw new Exception();
    }
    ```
    * 如果某方法调用了有 throws 声明的方法，则要么该方法添加 try-catch 语句来处理异常，要么继续将异常抛出，让更上一层的方法来处理异常

* 自定义异常
    * 语法规则
    ```
    class 自定义异常类 extends 异常类型{
    }
    ```
    * 例子
    ```
    public class DrankException extends Exception {
        public DrankException( String message ){
            super(message);
        }
    }
    ```

* 异常链
    * 应用场景：将某异常进行包装，转换成另一种异常，以统一进行处理
    ```
    public class DrankException extends Exception {
        public DrankException( String message ){
            super(message);
        }
    }
    public class ChainTest {
        public static void main(String[] args) {
            ChainTest ct = new ChainTest();
            try{
                ct.test2();
            }catch(RuntimeException e){
                e.printStackTrace();
            }
        }

        public void test1() throws DrankException{
            throw new DrankException("喝大了");
        }
        public void test2() throws RuntimeException{
            try{
                test1();            
            } catch( DrankException e ){
                RuntimeException newExc = new RuntimeException(e);
                throw newExc;
            }
        }
    }
    ```




